# Generated by Django 3.2.12 on 2022-04-02 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('ip', models.CharField(max_length=64)),
                ('port', models.IntegerField()),
                ('description', models.CharField(max_length=256)),
                ('CPU', models.IntegerField(default=1)),
                ('capacity', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('operatorDir', models.CharField(max_length=64)),
                ('imgDir', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'container',
            },
        ),
        migrations.CreateModel(
            name='DAG_node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_ID', models.IntegerField()),
                ('pos_x', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pos_y', models.DecimalField(decimal_places=2, max_digits=6)),
                ('node_type', models.CharField(default='task', max_length=64)),
                ('node_location', models.CharField(max_length=64)),
                ('App', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.app')),
            ],
            options={
                'db_table': 'DAG_node',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('file', models.FileField(blank=True, null=True, upload_to='operator')),
                ('filename', models.CharField(max_length=64, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('imagename', models.CharField(max_length=64, unique=True)),
                ('inputDir', models.CharField(max_length=64)),
                ('outputDir', models.CharField(max_length=64)),
                ('workFilename', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'operator',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('input', models.ImageField(blank=True, null=True, upload_to='task_img/input')),
                ('status', models.CharField(max_length=64)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.app')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Task_output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
            ],
            options={
                'db_table': 'task_output',
            },
        ),
        migrations.CreateModel(
            name='Task_node_wait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.CharField(max_length=512)),
                ('status', models.IntegerField()),
                ('localInputDir', models.CharField(max_length=64)),
                ('localOutputDir', models.CharField(max_length=64)),
                ('imageInputDir', models.CharField(max_length=64)),
                ('imageOutputDir', models.CharField(max_length=64)),
                ('inputs', models.CharField(max_length=512)),
                ('outputs', models.CharField(max_length=512)),
                ('ip', models.CharField(max_length=64)),
                ('port', models.IntegerField()),
                ('workFilename', models.CharField(max_length=64)),
                ('containername', models.CharField(max_length=256)),
                ('preWaitIds', models.CharField(max_length=64)),
                ('node_location', models.CharField(max_length=64)),
                ('renameInputs', models.CharField(max_length=512)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dag_node')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
            ],
            options={
                'db_table': 'task_node_wait',
            },
        ),
        migrations.CreateModel(
            name='Task_node_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dag_node')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
            ],
            options={
                'db_table': 'task_node_status',
            },
        ),
        migrations.CreateModel(
            name='Operator_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=64)),
                ('parameter_type', models.CharField(max_length=64)),
                ('description', models.CharField(default='', max_length=64)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operator')),
            ],
            options={
                'db_table': 'operator_parameter',
            },
        ),
        migrations.CreateModel(
            name='Operator_distribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containername', models.CharField(max_length=64, unique=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.container')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operator')),
            ],
            options={
                'db_table': 'operator_distribute',
            },
        ),
        migrations.CreateModel(
            name='Node_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('export', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dag_node')),
                ('operator_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operator_parameter')),
            ],
            options={
                'db_table': 'node_parameter',
            },
        ),
        migrations.CreateModel(
            name='Distribute_wait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.CharField(max_length=512)),
                ('status', models.IntegerField()),
                ('containername', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=64)),
                ('port', models.IntegerField()),
                ('filename', models.CharField(max_length=64)),
                ('filelocation', models.CharField(max_length=256)),
                ('operatorDir', models.CharField(max_length=64)),
                ('operator_distribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operator_distribute')),
            ],
            options={
                'db_table': 'distribute_wait',
            },
        ),
        migrations.CreateModel(
            name='DAG_node_circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_circle', models.IntegerField()),
                ('pos_x', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pos_y', models.DecimalField(decimal_places=2, max_digits=6)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dag_node')),
            ],
            options={
                'db_table': 'DAG_node_circle',
            },
        ),
        migrations.AddField(
            model_name='dag_node',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operator'),
        ),
        migrations.CreateModel(
            name='DAG_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.app')),
                ('from_node_circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_node_circle_id', to='app.dag_node_circle')),
                ('to_node_circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_node_circle_id', to='app.dag_node_circle')),
            ],
            options={
                'db_table': 'DAG_line',
            },
        ),
    ]
