# Generated by Django 3.2.12 on 2022-05-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_node_status_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='status',
            field=models.CharField(default='正常', max_length=64),
            preserve_default=False,
        ),
    ]
