# Generated by Django 3.2.12 on 2022-05-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='loading',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
