# Generated by Django 3.2.12 on 2022-05-22 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_operator_loading'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_node_wait',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
