# Generated by Django 3.2.12 on 2022-05-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_task_node_wait_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_node_wait',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
