# Generated by Django 3.2.12 on 2022-05-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_task_node_wait_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_node_status',
            name='server',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
