# Generated by Django 3.2.12 on 2022-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_task_node_status_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_node_status',
            name='server',
            field=models.IntegerField(null=True),
        ),
    ]
